### PR TITLE
removing mw.host.tags from otel yamls as mw.host.tags will be added from bifrost

### PR DESCRIPTION
**Pull request by bhogayatakb**

### CODE REVIEW

**Review by tejaskokje-mw — COMMENTED** [review]
What will happen to the host tags configured in the agent config file ?

**Comment by bhogayatakb** [comment]
> What will happen to the host tags configured in the agent config file ?

In all 3 cases. (host tags added via YAML, ENV or arguments)
tags will be passed to ingestion-rules API and bifrost will add the tags in the resource attributes section.

Let me verify if tags passed through YAMLs are also reaching to the API call

**Comment by bhogayatakb** [comment]
> What will happen to the host tags configured in the agent config file ?

Yes, as I expected, the tags passed via config yaml is also getting upto ingestion-rules API call,
therefore also making to the resource attributes !

**Review by tejaskokje-mw — APPROVED** [review]
LGTM

**Pull request closed without merging**
